# This workflow warns and then closes issues that have had no activity for a specified amount of time.
name: Mark and close stale issues

on:
  schedule:
  # Scheduled to run at 1:30 UTC everyday
  - cron: '30 1 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-issue-stale: 7
        days-before-issue-close: 2
        stale-issue-label: "status:stale"
        close-issue-reason: not_planned
        any-of-labels: "status:awaiting user response"
        stale-issue-message: >
          This issue has been marked as stale because it has been open for 7 days with no activity. It will be closed in 2 days if no further activity occurs.
        close-issue-message: >
          This issue was closed because it has been inactive for 9 days.
          Please post a new issue if you need further assistance. Thanks!
        # Label that can be assigned to issues to exclude them from being marked as stale
        exempt-issue-labels: 'override-stale'
